steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true","appengine:deploy", "-Dapp.deploy.projectId=anthony-bubble-pdf-service"]