#### Generate PDF With Google Cloud storage
POST http://localhost:8080/api/pdf
Content-Type: application/json

{
  "questions" : [
    {
      "title": "How is life different today compared to when you were a child?",
      "elements": [
        {
          "type": "text",
          "value": "How is life different today compared to when you were a child?"
        },
        {
          "type": "image",
          "value": "https://s3.amazonaws.com/appforest_uf/f1666453946962x421976841385394600/read-369040_1920.jpg"
        },
        {
          "type": "text",
          "value": "Section 3  (image is 363kb)"
        }
      ]
    },
    {
      "title": "What is your happiest childhood memory?",
      "elements": [
        {
          "type": "text",
          "value": "What is your happiest childhood memory?"
        },
        {
          "type": "text",
          "value": "section 2 (image is 166kb)"
        },
        {
          "type": "image",
          "value": "https://s3.amazonaws.com/appforest_uf/f1666453985248x435032636778127000/people-2572105_1920.jpg"
        }
      ]
    }
  ]
}

### Generate PDF and store it on Google Cloud Storage
POST http://localhost:8080/api/pdf
Content-Type: application/json

{
  "questions" : [
    {
      "title": "How is life different today compared to when you were a child?",
      "elements": [
        {
          "type": "text",
          "value": "How is life different today compared to when you were a child?"
        },
        {
          "type": "image",
          "value": "https://s3.amazonaws.com/appforest_uf/f1666453946962x421976841385394600/read-369040_1920.jpg"
        },
        {
          "type": "text",
          "value": "Section 3  (image is 363kb)"
        }
      ]
    },
    {
      "title": "What is your happiest childhood memory?",
      "elements": [
        {
          "type": "text",
          "value": "What is your happiest childhood memory?"
        },
        {
          "type": "text",
          "value": "section 2 (image is 166kb)"
        },
        {
          "type": "image",
          "value": "https://s3.amazonaws.com/appforest_uf/f1666453985248x435032636778127000/people-2572105_1920.jpg"
        }
      ]
    }
  ],
  "metadata" : {
    "bucketId" : "test-pdf-32",
    "pdfFileId" : "test-local-anthony.pdf",
    "labels" : [ "bubble.io", "kindred-tales", "test", "pdf" ]
  }
}

###
#"metadata": {
#"bucketId": "kindred-pdf-files",
#"pdfFileId": "1671397842129x624382778626539500_interior7Ctv5.pdf"
#}
#### Generate PDF from Nick example with image and without Cloud storage
POST http://localhost:8080/api/pdf
Content-Type: application/json

< samples_json/Nick-12_20_2022.json

#### Generate PDF from Nick example with image and without Cloud storage
POST http://localhost:8080/api/pdf
Content-Type: application/json

< samples_json/Nick-12_20_2022-no_images.json

#### Generate PDF from Nick example with image from AWS S3
POST http://localhost:8080/api/pdf
Content-Type: application/json

< samples_json/Nick-GCP_12_30_2022-images-s3.json

#### Generate PDF from Nick example with image from GCP
POST http://localhost:8080/api/pdf
Content-Type: application/json

< samples_json/Nick-GCP_12_30_2022-images-google-cloud.json

#### Generate PDF from Nick example with image from local filesystem
POST http://localhost:8080/api/pdf
Content-Type: application/json

< samples_json/Nick-GCP_12_30_2022-images-local.json

################## Download FULL Bucket items
GET http://localhost:8080/api/pdf/bucket?bucketId=kindred-tales-jv3hl7&keyPrefix=1670130473277x957049496090705900

#################
################# Download images from payload using different strategy
#################
## Top:   URL Stream Channel, HTTP Connection
## Bof: Http client, Http client 5

#### Download images with different strategy
#POST http://localhost:8080/api/pdf/download-images/URL_STREAM
POST http://localhost:8080/api/pdf/download-images/URL_STREAM_CHANNEL
#POST http://localhost:8080/api/pdf/download-images/URL_HTTP_CONNECTION
#POST http://localhost:8080/api/pdf/download-images/HTTP_CLIENT
#POST http://localhost:8080/api/pdf/download-images/HTTP_CLIENT_5
#POST http://localhost:8080/api/pdf/download-images/COMMONS_IO
Content-Type: application/json

#< sample-request-empty.json
#< samples_json/Nick-12_20_2022-no_images.json
#< samples_json/Nick-GCP_12_30_2022-images-s3.json
< samples_json/Nick-GCP_12_30_2022-images-google-cloud.json
#< samples_json/Nick-2023-01-01-JSON-GSURLs.json
#< samples_json/Nick-GCP_12_30_2022-images-local.json

